<%@ page import="java.util.*,br.com.filasus.model.*" %><%@ page contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%!private String h(Object v){return v==null?"":v.toString().replace("&","&amp;").replace("<","&lt;").replace(">","&gt;").replace("\"","&quot;");}%>
<%Usuario admin=(Usuario)session.getAttribute("usuarioLogado");Map<String,Integer> por=(Map<String,Integer>)request.getAttribute("porStatus");List<Mutirao> todos=(List<Mutirao>)request.getAttribute("todosMutiroes");if(por==null)por=Collections.emptyMap();if(todos==null)todos=Collections.emptyList();String ctx=request.getContextPath(),pageTitle="Relatórios",activeNav="relatorios";%>
<%@ include file="/WEB-INF/jspf/admin-shell-start.jspf" %>
<div class="admin-heading"><div><h1>Relatórios</h1><p>Indicadores consolidados de atendimento por mutirão.</p></div><button class="btn btn--outline" onclick="window.print()"><%=ico("fileText")%> Imprimir</button></div>
<form method="get" action="<%=ctx%>/admin/relatorios" class="card mb-4"><div class="card__header"><div><div class="card__title">Filtros</div><div class="card__description">Selecione uma operação para detalhar os resultados.</div></div></div><div class="card__body admin-actions"><select class="select" name="idMutirao" style="max-width:420px"><option value="">Todos os mutirões</option><%for(Mutirao m:todos){%><option value="<%=m.getId()%>" <%=String.valueOf(m.getId()).equals(request.getParameter("idMutirao"))?"selected":""%>><%=h(m.getTipo())%> — <%=h(m.getData())%></option><%}%></select><button class="btn btn--primary"><%=ico("search")%> Aplicar filtro</button></div></form>
<div class="grid grid-3 mb-4"><div class="stat-card"><div class="stat-card__icon stat-card__icon--teal"><%=ico("calendar")%></div><div class="stat-card__label">Mutirões</div><div class="stat-card__value"><%=request.getAttribute("totalMutiroes")%></div></div><div class="stat-card"><div class="stat-card__icon stat-card__icon--amber"><%=ico("list")%></div><div class="stat-card__label">Filas</div><div class="stat-card__value"><%=request.getAttribute("totalFilas")%></div></div><div class="stat-card"><div class="stat-card__icon stat-card__icon--violet"><%=ico("ticket")%></div><div class="stat-card__label">Senhas</div><div class="stat-card__value"><%=request.getAttribute("totalItens")%></div></div></div>
<section class="card"><div class="card__header"><div><div class="card__title">Senhas por situação</div><div class="card__description">Quantidade registrada em cada etapa do fluxo.</div></div></div><div class="table-responsive"><table class="table"><thead><tr><th>Situação</th><th>Quantidade</th></tr></thead><tbody><%if(por.isEmpty()){%><tr><td colspan="2"><div class="empty-state"><div class="empty-state__title">Sem dados para o filtro</div><div class="empty-state__message">Escolha outro mutirão ou aguarde novos atendimentos.</div></div></td></tr><%}else for(Map.Entry<String,Integer> e:por.entrySet()){%><tr><td><span class="badge badge--slate"><%=h(e.getKey())%></span></td><td><strong><%=e.getValue()%></strong></td></tr><%}%></tbody></table></div></section>
<%@ include file="/WEB-INF/jspf/admin-shell-end.jspf" %>
