<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" import="java.util.*,br.com.filasus.model.*,br.com.filasus.model.enums.StatusItemFila" %>
<%!
private String h(Object v){if(v==null)return "";return v.toString().replace("&","&amp;").replace("<","&lt;").replace(">","&gt;").replace("\"","&quot;");}
private String senha(ItemFila i){return "F"+i.getIdFila()+"-"+String.format("%03d",i.getSequenciaItemFila());}
private String nome(ItemFila i){return i.getPaciente()==null?i.getCpfPaciente():i.getPaciente().getNome();}
%>
<%
Usuario usuario=(Usuario)request.getAttribute("usuario");
Mutirao mutirao=(Mutirao)request.getAttribute("mutirao");
List<Fila> filas=(List<Fila>)request.getAttribute("filas");
List<ItemFila> itens=(List<ItemFila>)request.getAttribute("itens");
if(filas==null)filas=Collections.emptyList();if(itens==null)itens=Collections.emptyList();
String ctx=request.getContextPath(),pageTitle="Painel",activeNav="dashboard";
long aguardando=itens.stream().filter(ItemFila::isAguardando).count();
long prioritarios=itens.stream().filter(i->i.isAguardando()&&i.getFila()!=null&&i.getFila().getTipo()!=null&&"PRIORITARIO".equals(i.getFila().getTipo().name())).count();
long chamados=itens.stream().filter(i->i.getStatus()==StatusItemFila.CHAMADO||i.getStatus()==StatusItemFila.EM_ATENDIMENTO).count();
long atendidos=itens.stream().filter(i->i.getStatus()==StatusItemFila.ATENDIDO).count();
long ausentes=itens.stream().filter(i->i.getStatus()==StatusItemFila.AUSENTE).count();
long mediaEspera=itens.isEmpty()?0:Math.round(itens.stream().mapToLong(ItemFila::getTempoEsperaMinutos).average().orElse(0));
%>
<%@ include file="/WEB-INF/jspf/atendente-shell-start.jspf" %>
<style>
.queue-cards-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:16px;align-items:stretch}.queue-now-card{display:flex;flex-direction:column;height:100%}.queue-now-current{display:flex;align-items:center;justify-content:space-between;gap:12px;padding:12px;border-radius:var(--radius);background:var(--slate-50);border:1px solid var(--border);flex-wrap:wrap}.queue-now-current--active{background:linear-gradient(135deg,var(--teal-50),var(--emerald-50));border-color:var(--teal-200)}.queue-now-current__label{font-size:11px;font-weight:700;text-transform:uppercase;letter-spacing:.05em;color:var(--text-muted)}.queue-now-current__password{font-family:var(--font-mono);font-weight:700;font-size:22px;color:var(--teal-700)}.queue-now-current__name{font-size:13px;color:var(--text-muted);margin-top:2px;max-width:220px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.live-dot{display:inline-block;width:8px;height:8px;border-radius:50%;background:var(--emerald-500);animation:live-pulse 1.5s infinite}@keyframes live-pulse{50%{opacity:.5;transform:scale(.8)}}@media(max-width:1024px){.queue-cards-grid{grid-template-columns:repeat(2,1fr)}}@media(max-width:640px){.queue-cards-grid{grid-template-columns:1fr}}
</style>
<div class="server-page-heading"><h1>Painel do Atendente</h1><p>Visão geral da operação de hoje</p></div>
<%if(request.getAttribute("sucesso")!=null){%><div class="alert alert--success server-message"><%=ico("check")%><div><%=h(request.getAttribute("sucesso"))%></div></div><%}if(request.getAttribute("erro")!=null){%><div class="alert alert--danger server-message"><%=ico("alert")%><div><%=h(request.getAttribute("erro"))%></div></div><%}%>
<%if(mutirao==null){%>
<div class="card"><div class="empty-state"><div class="empty-state__icon"><%=ico("alert")%></div><div class="empty-state__title">Nenhum mutirão aberto</div><div class="empty-state__message">Não há mutirão em andamento no momento. Verifique com a administração.</div></div></div>
<%}else{%>
<section class="card mb-4"><div class="card__body server-session"><div class="server-session__icon"><%=ico("heart")%></div><div style="flex:1;min-width:200px"><div style="display:flex;gap:8px;align-items:center;flex-wrap:wrap"><h2 style="font-size:18px"><%=h(mutirao.getTipo())%></h2><span class="badge badge--emerald"><%=h(mutirao.getStatus().getDescricao())%></span></div><p style="font-size:13px;color:var(--text-muted);margin-top:4px;display:flex;gap:6px;align-items:center;flex-wrap:wrap"><span style="display:inline-flex;gap:4px;align-items:center"><%=ico("mapPin")%><%=h(mutirao.getLocal())%></span><span>·</span><span style="display:inline-flex;gap:4px;align-items:center"><%=ico("calendar")%><%=h(mutirao.getData())%></span></p></div><a class="btn btn--outline btn--sm" href="<%=ctx%>/atendente/cadastrar-paciente"><%=ico("userPlus")%> Cadastrar Paciente</a><a class="btn btn--primary btn--sm" href="<%=ctx%>/atendente/fila"><%=ico("list")%> Gerenciar Fila</a></div></section>
<div class="grid grid-3 mb-4">
<div class="stat-card"><div class="stat-card__icon stat-card__icon--teal"><%=ico("clock")%></div><div class="stat-card__label">Aguardando</div><div class="stat-card__value"><%=aguardando%></div><div class="stat-card__hint">Na fila agora</div></div>
<div class="stat-card"><div class="stat-card__icon stat-card__icon--amber"><%=ico("shield")%></div><div class="stat-card__label">Prioritários</div><div class="stat-card__value"><%=prioritarios%></div><div class="stat-card__hint">Aguardando prioridade</div></div>
<div class="stat-card"><div class="stat-card__icon stat-card__icon--violet"><%=ico("stethoscope")%></div><div class="stat-card__label">Em Atendimento</div><div class="stat-card__value"><%=chamados%></div><div class="stat-card__hint">Chamados / em consulta</div></div>
<div class="stat-card"><div class="stat-card__icon stat-card__icon--emerald"><%=ico("check")%></div><div class="stat-card__label">Atendidos</div><div class="stat-card__value"><%=atendidos%></div><div class="stat-card__hint">Concluídos hoje</div></div>
<div class="stat-card"><div class="stat-card__icon stat-card__icon--rose"><%=ico("ban")%></div><div class="stat-card__label">Ausentes</div><div class="stat-card__value"><%=ausentes%></div><div class="stat-card__hint">Não compareceram</div></div>
<div class="stat-card"><div class="stat-card__icon stat-card__icon--slate"><%=ico("activity")%></div><div class="stat-card__label">Espera Média</div><div class="stat-card__value"><%=mediaEspera%> min</div><div class="stat-card__hint">Tempo médio de espera</div></div>
</div>
<section class="card mb-4"><div class="card__header"><div><div class="card__title">Fila em Tempo Real</div><div class="card__description"><span class="live-dot"></span><span style="margin-left:6px">Dados atualizados ao recarregar a página</span></div></div><a class="btn btn--ghost btn--sm" href="<%=ctx%>/atendente/dashboard"><%=ico("refresh")%> Atualizar</a></div><div class="card__body">
<%if(filas.isEmpty()){%><div class="empty-state"><div class="empty-state__icon"><%=ico("list")%></div><div class="empty-state__title">Sem filas configuradas</div><div class="empty-state__message">Este mutirão ainda não possui filas de atendimento.</div></div><%}else{%><div class="queue-cards-grid"><%for(Fila fila:filas){List<ItemFila> daFila=new ArrayList<>();for(ItemFila i:itens)if(i.getIdFila()==fila.getId())daFila.add(i);long espera=daFila.stream().filter(ItemFila::isAguardando).count();long pri=daFila.stream().filter(i->i.isAguardando()&&fila.getTipo()!=null&&"PRIORITARIO".equals(fila.getTipo().name())).count();ItemFila atual=null;for(ItemFila i:daFila)if(i.getStatus()==StatusItemFila.CHAMADO||i.getStatus()==StatusItemFila.EM_ATENDIMENTO){atual=i;break;}%>
<article class="card queue-now-card"><div style="display:flex;align-items:center;justify-content:space-between;gap:8px;padding:14px 16px;border-bottom:1px solid var(--border)"><div><div style="font-size:14px;font-weight:600"><%=h(fila.getNome())%></div><div style="font-size:11px;color:var(--text-muted);margin-top:2px">Fila <span class="font-mono">F<%=fila.getId()%></span> · <%=h(fila.getTipo()==null?"Comum":fila.getTipo().getDescricao())%></div></div><span class="badge badge--slate"><%=espera%> aguardando</span></div><div style="padding:16px;flex:1;display:flex;flex-direction:column"><div class="queue-now-current <%=atual!=null?"queue-now-current--active":""%>" style="flex:1"><div><div class="queue-now-current__label"><%=atual!=null?"Em atendimento agora":"Ninguém chamado"%></div><%if(atual!=null){%><div class="queue-now-current__password"><%=senha(atual)%></div><div class="queue-now-current__name"><%=h(nome(atual))%></div><%}else{%><div style="font-size:13px;color:var(--text-muted);margin-top:6px">Fila pronta para chamada.</div><%}%></div><form method="post" action="<%=ctx%>/fila/chamar-proximo"><input type="hidden" name="idFila" value="<%=fila.getId()%>"><input type="hidden" name="origem" value="dashboard"><button class="btn btn--primary btn--sm" <%=espera==0?"disabled":""%>><%=ico("play")%> Chamar Próximo</button></form></div><div style="display:flex;align-items:center;gap:6px;margin-top:10px;font-size:12px;color:var(--amber-700)"><%=ico("shield")%><%=pri%> prioritário(s)</div></div></article>
<%}%></div><%}%></div></section>
<%if(prioritarios>0){%><div class="alert alert--warning"><%=ico("shield")%><div><div class="alert__title">Pacientes prioritários aguardando</div><div class="alert__message">Há <%=prioritarios%> paciente(s) prioritário(s) na fila. O serviço aplicará as regras de chamada configuradas.</div></div></div><%}%>
<%}%>
<%@ include file="/WEB-INF/jspf/atendente-shell-end.jspf" %>
