<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" import="java.util.*,br.com.filasus.model.*,br.com.filasus.model.enums.StatusItemFila" %>
<%!
private String h(Object v){if(v==null)return "";return v.toString().replace("&","&amp;").replace("<","&lt;").replace(">","&gt;").replace("\"","&quot;");}
private String badge(StatusItemFila s){if(s==StatusItemFila.CHAMADO)return "badge--amber";if(s==StatusItemFila.EM_ATENDIMENTO)return "badge--teal";if(s==StatusItemFila.ATENDIDO)return "badge--emerald";if(s==StatusItemFila.AUSENTE)return "badge--rose";return "badge--slate";}
private String senha(ItemFila i){return "F"+i.getIdFila()+"-"+String.format("%03d",i.getSequenciaItemFila());}
private String nome(ItemFila i){return i.getPaciente()==null?i.getCpfPaciente():i.getPaciente().getNome();}
%>
<%
Usuario usuario=(Usuario)request.getAttribute("usuario");Mutirao mutirao=(Mutirao)request.getAttribute("mutirao");
List<Fila> filas=(List<Fila>)request.getAttribute("filas");List<ItemFila> itens=(List<ItemFila>)request.getAttribute("itens");
if(filas==null)filas=Collections.emptyList();if(itens==null)itens=Collections.emptyList();
String ctx=request.getContextPath(),pageTitle="Gerenciar Fila",activeNav="fila";
int idSelecionada=filas.isEmpty()?0:filas.get(0).getId();try{if(request.getParameter("fila")!=null)idSelecionada=Integer.parseInt(request.getParameter("fila"));}catch(NumberFormatException ignored){}
Fila filaSelecionada=null;for(Fila f:filas)if(f.getId()==idSelecionada){filaSelecionada=f;break;}if(filaSelecionada==null&&!filas.isEmpty()){filaSelecionada=filas.get(0);idSelecionada=filaSelecionada.getId();}
List<ItemFila> itensFila=new ArrayList<>();for(ItemFila i:itens)if(i.getIdFila()==idSelecionada)itensFila.add(i);
long aguardando=itens.stream().filter(ItemFila::isAguardando).count();long prioritarios=itens.stream().filter(i->i.isAguardando()&&i.getFila()!=null&&i.getFila().getTipo()!=null&&"PRIORITARIO".equals(i.getFila().getTipo().name())).count();long chamados=itens.stream().filter(i->i.getStatus()==StatusItemFila.CHAMADO||i.getStatus()==StatusItemFila.EM_ATENDIMENTO).count();long atendidos=itens.stream().filter(i->i.getStatus()==StatusItemFila.ATENDIDO).count();long ausentes=itens.stream().filter(i->i.getStatus()==StatusItemFila.AUSENTE).count();long media=itens.isEmpty()?0:Math.round(itens.stream().mapToLong(ItemFila::getTempoEsperaMinutos).average().orElse(0));
long esperaSelecionada=itensFila.stream().filter(ItemFila::isAguardando).count();ItemFila atual=null;for(ItemFila i:itensFila)if(i.getStatus()==StatusItemFila.CHAMADO||i.getStatus()==StatusItemFila.EM_ATENDIMENTO){atual=i;break;}
%>
<%@ include file="/WEB-INF/jspf/atendente-shell-start.jspf" %>
<style>
.call-next-btn{display:flex;align-items:center;justify-content:center;gap:10px;padding:10px 24px;font-size:15px;font-weight:700;background:linear-gradient(135deg,var(--teal-600),var(--emerald-600));color:#fff;border:0;border-radius:var(--radius-lg);cursor:pointer;box-shadow:0 8px 24px -8px rgba(13,148,136,.4)}.call-next-btn:hover:not(:disabled){transform:translateY(-1px);box-shadow:0 12px 28px -8px rgba(13,148,136,.5)}.call-next-btn:disabled{opacity:.5;cursor:not-allowed}.call-next-btn__icon{width:24px;height:24px;border-radius:50%;background:rgba(255,255,255,.2);display:flex;align-items:center;justify-content:center}
.now-serving{display:flex;flex-direction:column;gap:12px;padding:16px;border-radius:var(--radius);background:linear-gradient(135deg,var(--teal-50),var(--emerald-50));border:1px solid var(--teal-200)}.now-serving--empty{background:var(--surface-2);border:1px dashed var(--border-strong);align-items:center;justify-content:center;padding:24px;text-align:center}.now-serving__label{font-size:11px;font-weight:700;text-transform:uppercase;letter-spacing:.05em;color:var(--text-muted)}.now-serving__content{display:flex;align-items:center;gap:24px;min-width:0}.now-serving__patient{display:flex;align-items:center;gap:16px;min-width:0;flex:1 1 auto}.now-serving__password{font-family:var(--font-mono);font-weight:700;font-size:36px;color:var(--teal-700);line-height:1;white-space:nowrap;word-break:normal;flex-shrink:0}.now-serving__name{font-size:16px;font-weight:600;margin-top:4px}.now-serving__meta{font-size:12px;color:var(--text-muted);margin-top:2px;display:flex;align-items:center;gap:4px}.now-serving__actions{display:grid;grid-template-columns:repeat(2,minmax(170px,1fr));gap:8px;margin-left:auto;flex:0 0 auto}.now-serving__actions .btn{width:100%;white-space:nowrap;justify-content:flex-start}
.live-dot{display:inline-block;width:8px;height:8px;border-radius:50%;background:var(--emerald-500);animation:live-pulse 1.5s infinite}@keyframes live-pulse{50%{opacity:.5;transform:scale(.8)}}.queue-single-card .card__header{display:flex;align-items:center;justify-content:space-between;gap:16px;padding:16px 20px;flex-wrap:wrap}.queue-single-card .card__body{padding:16px 20px}.queue-single-card .card__body--p0{padding:0}.queue-list-header,.queue-list-item{display:grid;grid-template-columns:80px 1fr 110px 110px 70px 180px;gap:12px;align-items:center}.queue-list-header{padding:12px 20px;background:var(--surface-2);border-bottom:1px solid var(--border);font-size:11px;font-weight:600;text-transform:uppercase;color:var(--text-muted);letter-spacing:.03em}.queue-list-item{padding:14px 20px;border-bottom:1px solid var(--border);font-size:14px}.queue-list-item:last-child{border-bottom:0}.queue-list-empty{padding:40px 20px;text-align:center;color:var(--text-muted);font-size:14px}.queue-tabs{display:flex;gap:4px;overflow-x:auto;margin-bottom:16px;border-bottom:1px solid var(--border)}.queue-tabs .tab{white-space:nowrap;text-decoration:none}.queue-actions{display:flex;gap:6px;flex-wrap:wrap}
@media(max-width:980px){.now-serving__content{align-items:flex-start;flex-direction:column}.now-serving__actions{width:100%;margin-left:0}.now-serving__actions .btn{justify-content:center}}
@media(max-width:768px){.queue-list-header,.queue-list-item{grid-template-columns:70px 1fr auto}.queue-list-header>*:nth-child(n+4),.queue-list-item>*:nth-child(n+4){display:none}.call-next-btn{width:100%}.queue-single-card .card__header>div{width:100%}}
@media(max-width:480px){.now-serving__patient{align-items:flex-start;flex-direction:column;gap:8px}.now-serving__actions{grid-template-columns:1fr}}
</style>
<div class="server-page-heading"><h1>Gerenciar Fila</h1><p><%=mutirao==null?"Controle de chamadas em tempo real":h(mutirao.getTipo())%></p></div>
<%if(request.getAttribute("sucesso")!=null){%><div class="alert alert--success server-message"><%=ico("check")%><div><%=h(request.getAttribute("sucesso"))%></div></div><%}if(request.getAttribute("erro")!=null){%><div class="alert alert--danger server-message"><%=ico("alert")%><div><%=h(request.getAttribute("erro"))%></div></div><%}%>
<%if(mutirao==null){%><div class="card"><div class="card__body"><div class="empty-state"><div class="empty-state__icon"><%=ico("alert")%></div><div class="empty-state__title">Nenhum mutirão aberto</div><div class="empty-state__message">Não há mutirão em andamento para gerenciar a fila.</div></div></div></div><%}else{%>
<div class="grid grid-3 mb-4">
  <div class="stat-card"><div class="stat-card__icon stat-card__icon--teal"><%=ico("users")%></div><div class="stat-card__label">Aguardando</div><div class="stat-card__value"><%=aguardando%></div><div class="stat-card__hint">Na fila agora</div></div>
  <div class="stat-card"><div class="stat-card__icon stat-card__icon--amber"><%=ico("shield")%></div><div class="stat-card__label">Prioritários</div><div class="stat-card__value"><%=prioritarios%></div><div class="stat-card__hint">Na fila agora</div></div>
  <div class="stat-card"><div class="stat-card__icon stat-card__icon--violet"><%=ico("play")%></div><div class="stat-card__label">Chamados</div><div class="stat-card__value"><%=chamados%></div><div class="stat-card__hint">Chamados / em consulta</div></div>
  <div class="stat-card"><div class="stat-card__icon stat-card__icon--emerald"><%=ico("check")%></div><div class="stat-card__label">Atendidos</div><div class="stat-card__value"><%=atendidos%></div><div class="stat-card__hint">Concluídos</div></div>
  <div class="stat-card"><div class="stat-card__icon stat-card__icon--rose"><%=ico("ban")%></div><div class="stat-card__label">Ausentes</div><div class="stat-card__value"><%=ausentes%></div><div class="stat-card__hint">Não compareceram</div></div>
  <div class="stat-card"><div class="stat-card__icon stat-card__icon--slate"><%=ico("clock")%></div><div class="stat-card__label">Espera Média</div><div class="stat-card__value"><%=media%> min</div><div class="stat-card__hint">Tempo médio de espera</div></div>
</div>
<div style="display:flex;align-items:center;gap:8px;margin-bottom:12px;font-size:12px;color:var(--text-muted)"><span class="live-dot"></span>Dados atualizados ao recarregar a página <a class="btn btn--ghost btn--sm" href="<%=ctx%>/atendente/fila?fila=<%=idSelecionada%>"><%=ico("refresh")%> Atualizar</a></div>
<nav class="queue-tabs" aria-label="Filas"><%for(Fila f:filas){long n=itens.stream().filter(i->i.getIdFila()==f.getId()&&i.isAguardando()).count();%><a class="tab <%=f.getId()==idSelecionada?"tab--active":""%>" href="<%=ctx%>/atendente/fila?fila=<%=f.getId()%>"><%=h(f.getNome())%><span class="tab__count"><%=n%></span></a><%}%></nav>
<section class="card queue-single-card">
  <div class="card__header" style="border-bottom:1px solid var(--border)"><div><div class="card__title"><%=filaSelecionada==null?"Fila":h(filaSelecionada.getNome())%></div><div class="card__description"><%=esperaSelecionada%> <%=esperaSelecionada==1?"paciente aguardando":"pacientes aguardando"%> · Prefixo <span class="font-mono">F<%=idSelecionada%></span></div></div><form method="post" action="<%=ctx%>/fila/chamar-proximo"><input type="hidden" name="idFila" value="<%=idSelecionada%>"><button class="call-next-btn" <%=esperaSelecionada==0?"disabled":""%>><span class="call-next-btn__icon"><%=ico("play")%></span>Chamar Próximo</button></form></div>
  <div class="card__body">
  <%if(atual==null){%><div class="now-serving now-serving--empty"><div class="empty-state" style="padding:8px"><div class="empty-state__icon" style="width:32px;height:32px;margin-bottom:6px"><%=ico("play")%></div><div class="empty-state__title" style="font-size:13px">Em atendimento agora</div><div class="empty-state__message" style="font-size:12px">Nenhum paciente chamado nesta fila. Clique em “Chamar Próximo” para iniciar.</div></div></div>
  <%}else{%><div class="now-serving"><div style="display:flex;align-items:center;justify-content:space-between;gap:12px;flex-wrap:wrap"><div class="now-serving__label"><%=atual.getStatus()==StatusItemFila.EM_ATENDIMENTO?"Em atendimento agora":"Chamado · aguardando paciente"%></div><span class="badge <%=badge(atual.getStatus())%>"><%=h(atual.getStatus().getDescricao())%></span></div><div class="now-serving__content"><div class="now-serving__patient"><div class="now-serving__password"><%=senha(atual)%></div><div style="padding-bottom:6px"><div class="now-serving__name"><%=h(nome(atual))%></div><div class="now-serving__meta"><%=h(filaSelecionada==null?"":filaSelecionada.getNome())%> · espera de <%=atual.getTempoEsperaMinutos()%> min</div></div></div><%if(atual.getStatus()==StatusItemFila.CHAMADO){%><form method="post" action="<%=ctx%>/atendente/fila/status" class="now-serving__actions"><input type="hidden" name="idFila" value="<%=atual.getIdFila()%>"><input type="hidden" name="sequencia" value="<%=atual.getSequenciaItemFila()%>"><input type="hidden" name="filaSelecionada" value="<%=idSelecionada%>"><button class="btn btn--outline btn--sm" name="acao" value="chamar_novamente"><%=ico("volume")%> Chamar Novamente</button><button class="btn btn--outline btn--sm" name="acao" value="ausente" onclick="return confirm('Marcar esta senha como ausente?')"><%=ico("ban")%> Marcar Ausente</button><button class="btn btn--outline btn--sm" name="acao" value="remarcar" onclick="return confirm('Remarcar o paciente no final da fila?')"><%=ico("refresh")%> Remarcar</button><button class="btn btn--outline btn--sm" name="acao" value="aguardando"><%=ico("arrowLeft")%> Devolver à Fila</button></form><%}else{%><div class="now-serving__meta" style="margin-left:auto">O médico assumiu este atendimento.</div><%}%></div></div><%}%>
  </div>
  <div class="card__body card__body--p0" style="border-top:1px solid var(--border)">
    <%if(esperaSelecionada==0){%><div class="queue-list-empty">Não há pacientes aguardando nesta fila.</div><%}else{%>
    <div class="queue-list-header"><div>Senha</div><div>Paciente</div><div>Prioridade</div><div>Status</div><div>Espera</div><div>Ações</div></div>
    <div style="max-height:400px;overflow-y:auto"><%for(ItemFila i:itensFila){if(!i.isAguardando())continue;%><div class="queue-list-item"><div class="font-mono" style="font-weight:700;font-size:15px"><%=senha(i)%></div><div><div style="font-weight:500"><%=h(nome(i))%></div><div style="font-size:12px;color:var(--text-muted)"><%=h(i.getCpfPaciente())%></div></div><div><span class="badge <%=i.getFila()!=null&&i.getFila().getTipo()!=null&&"PRIORITARIO".equals(i.getFila().getTipo().name())?"badge--amber":"badge--slate"%>"><%=i.getFila()!=null&&i.getFila().getTipo()!=null?h(i.getFila().getTipo().getDescricao()):"Comum"%></span></div><div><span class="badge badge--slate"><%=h(i.getStatus().getDescricao())%></span></div><div><%=i.getTempoEsperaMinutos()%> min</div><div><form method="post" action="<%=ctx%>/fila/chamar-proximo"><input type="hidden" name="idFila" value="<%=i.getIdFila()%>"><button class="btn btn--primary btn--sm"><%=ico("play")%> Chamar</button></form></div></div><%}%></div><%}%>
  </div>
</section>
<%}%>
<%@ include file="/WEB-INF/jspf/atendente-shell-end.jspf" %>
